In [0]:
import numpy as np

In [0]:
A = np.matrix([[1,2,3,4],
               [4,3,2,1],
               [3,4,1,2],
               [2,1,4,3]])

In [0]:
A ** 2 - 24


matrix([[2, 0, 2, 0],
        [0, 2, 0, 2],
        [2, 0, 2, 0],
        [0, 2, 0, 2]])

In [0]:
B = np.matrix([[2,4,1,3],
               [4,2,3,1],
               [1,3,2,4],
               [3,1,4,2]])

In [0]:
A * B

matrix([[25, 21, 29, 25],
        [25, 29, 21, 25],
        [29, 25, 25, 21],
        [21, 25, 25, 29]])

In [0]:
B * A

matrix([[27, 23, 27, 23],
        [23, 27, 23, 27],
        [27, 23, 27, 23],
        [23, 27, 23, 27]])

In [0]:
A2 = np.matrix([[1,-1],
               [2,1]])

In [0]:
A2 ** 2 - 2 * A2 + 3

matrix([[0, 3],
        [3, 0]])

In [0]:
B2 = np.matrix([[1,0],
                [0,1]])
x = np.linalg.solve(A2,B2)
x

matrix([[ 0.33333333,  0.33333333],
        [-0.66666667,  0.33333333]])